#!/bin/bash

. ./.node passive
PATH=${node%/*}:$PATH

isTTY=$(node -p -e "Boolean(process.stdout.isTTY)")
[ $isTTY == "false" ] && exec="winpty node" || exec=node

$exec ./lib/xcraft/bin/xcraft.js $@
