#!/bin/sh

. ./.node passive

PATH=${node%/*}:$PATH

if [ -f "./node_modules/.bin/node-debug" ]; then
  ./node_modules/.bin/node-debug -p 8181 scripts/zog.js $@
else
  echo "Install node-inspector first"
  echo "$ npm install node-inspector"
fi
